### ISSUE TITLE
built for production with uglify turned on - error 

### ISSUE THREAD

**Issue by jschimmoeller** [codemeasandwich/redux-auto#6]
very early in my investigation but it appears if uglify is turned on redux-auto blows up

main.bf5842ef.js:1 Uncaught TypeError: (("pending" === n) || ((!("fulfilled" === n)) && u)) is not iterable
    at y.(anonymous function) (https://launchpad.star2star.net/main.bf5842ef.js:1:77478)
    at https://launchpad.star2star.net/main.bf5842ef.js:1:1286327
    at y (https://launchpad.star2star.net/main.bf5842ef.js:1:650250)
    at t (https://launchpad.star2star.net/main.bf5842ef.js:1:79597)
    at https://launchpad.star2star.net/main.bf5842ef.js:1:1328567
    at dispatch (https://launchpad.star2star.net/main.bf5842ef.js:1:1287480)
    at Object.l.(anonymous function).(anonymous function) [as dashboard] (https://launchpad.star2star.net/main.bf5842ef.js:1:78999)
    at t.value (https://launchpad.star2star.net/main.bf5842ef.js:1:1637823)
    at Object.N (https://launchpad.star2star.net/main.bf5842ef.js:1:1347789)
    at Object.invokeGuardedCallback (https://launchpad.star2star.net/main.bf5842ef.js:1:1347068)

**Comment by codemeasandwich** [comment]
Hi @jschimmoeller 
What is your stack-trace when source mapping enabled?
Can you also share your action file that trigger the error?

**Comment by jschimmoeller** [comment]
sorry for the delay but had to do work stuff.  

to make this easier for you to resolve I went ahead and created a git repo and the readme explains this in details; below is the git repo:
https://github.com/jschimmoeller/prod-redux-auto-uglify

thanks
james

**Comment by codemeasandwich** [comment]
**Fixed** and live as **v1.9.4** on npm

**Comment by jschimmoeller** [comment]
Thanks
